version: '3'

volumes:
  pg_volume_prod:
  media_volume_prod:
  static_volume_prod:

services:
  postgres_db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_volume_prod:/var/lib/postgresql/data/

  backend:
    depends_on:
      - postgres_db
    image: grigoriev1991/kittygram_backend
    env_file: .env
    volumes:
      - media_volume_prod:/media
      - static_volume_prod:/backend_static

  frontend:
    image: grigoriev1991/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume_prod:/frontend_static

  gateway:
    image: grigoriev1991/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - media_volume_prod:/backend_media
      - static_volume_prod:/staticfiles
