version: '3'

volumes:
  pg_volume:
  media_volume:
  static_volume:

services:
  postgres_db:
    build: postgres:13
    env_file: .env
    volumes:
      - pg_volume:/var/lib/postgresql/data/
  backend:
    depends_on:
      - postgres_db
    build: grigoriev1991/kittygram_backend
    env_file: .env
    volumes:
      - media_volume:/kittygram/media
      - static_volume:/backend_static
  frontend:
    build: grigoriev1991/kittygram_frontend
    env_file: .env
    volumes:
      - static_volume:/static
    command: cp -r /app/build/. /static/
  gateway:
    build: grigoriev1991/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - media_volume:/home/kittygram/media
      - static_volume:/home/kittygram/static
