version: '3'

volumes:
  pg_volume:
  media_volume:
  static_volume:

services:
  postgres_db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_volume:/var/lib/postgresql/data/

  backend:
    depends_on:
      - postgres_db
    build: ./backend/
    env_file: .env
    volumes:
      - media_volume:/media
      - static_volume:/backend_static

  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - media_volume:/media
      - static_volume:/staticfiles
